#!/usr/bin/env bash
set -e
log() {
	echo -e "cljog: $@"
}

error_exit() {
	echo -e "cljog: $@" 1>&2
	exit 1
}

define(){ IFS='\n' read -r -d '' ${1} || true; }

[[ "$BASH_VERSION" < "4" ]] && error_exit "Bash version 4+ is required"

hash clojure 2>/dev/null || error_exit 'Clojure tools not found. Refer https://clojure.org/guides/deps_and_cli'

CLJ_OPTS='-J-Xms256m -J-Xmx256m -J-client -J-XX:MaxMetaspaceSize=100m -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-XX:+UseConcMarkSweepGC -J-XX:+CMSClassUnloadingEnabled -J-Xverify:none -J-Dclojure.spec.skip-macros=true'
VERSION=0.2.0

run_script(){ # path-to-script.clj & args
	local args='['
	for arg in "${@:2}";do
		args="$args \"$arg\""
	done
	args="$args ]"

	define clj_script <<EOF
;Fix for modifyable URLClassLoaders for supporting Java9 and up (required for pomegranate 1.0.0+). Refer:
; - https://github.com/cemerick/pomegranate#urlclassloader-modifiability
; - https://github.com/lambdaisland/kaocha/blob/master/src/kaocha/classpath.clj
(do
  (require '[dynapath.util])

  (defn- ensure-compiler-loader []
    (when-not (bound? Compiler/LOADER)
      (.bindRoot Compiler/LOADER (clojure.lang.DynamicClassLoader. (clojure.lang.RT/baseLoader)))))

  (defn- classloader-hierarchy []
    (ensure-compiler-loader)
    (let [loader (deref Compiler/LOADER)]
      (.setContextClassLoader (.. Thread currentThread) loader)
      (->> loader
           (iterate (fn [x] (.getParent ^ClassLoader x)))
           (take-while boolean))))

  (require '[cemerick.pomegranate])

  (defn deps [m]
    (cemerick.pomegranate/add-dependencies
      :classloader (last (filter dynapath.util/addable-classpath? (classloader-hierarchy)))
      :coordinates m
      :repositories (merge cemerick.pomegranate.aether/maven-central {"clojars" "https://clojars.org/repo"})))

  (def ^:dynamic *cljog-version* "$VERSION")
  (def ^:dynamic *cwd* (System/getProperty "user.dir"))
  (def ^:dynamic *script* "$1")

  (binding [*command-line-args* $args]
    (load-file *script*))
  nil)
EOF

	#language=clj
	local DEPS='
  {:deps          {com.cemerick/pomegranate {:mvn/version "1.1.0" :exclusions [commons-logging]}
                   org.slf4j/slf4j-nop      {:mvn/version "1.7.22"}}
   :override-deps {org.slf4j/slf4j-api      {:mvn/version "1.7.22"}
                   org.slf4j/jcl-over-slf4j {:mvn/version "1.7.22"}}}'
  exec clojure $CLJ_OPTS -Sdeps "$DEPS" -e "$clj_script"
}

update_clis(){ #namespaces
	local namespaces=$1
	local tmpdir=$(dirname $(mktemp -u))
	define clj_script <<EOF
(deps '[[clj-http "3.10.0"]
        [cheshire "5.9.0"]])

(require
  '[clj-http.client :as client]
  '[clojure.string :as str])

(def groups (some-> *command-line-args* seq first (str/split #",")))
(def connection-pool-defaults {:timeout 5 :threads 4 :insecure? false :default-per-route 10})

(defn- ->dep [group-key artifact-key version-key m]
  (when-let [group (group-key m)]
    (let [cli (str group \/ (artifact-key m))]
      [(symbol cli) (version-key m)])))

(defn- fetch-from-clojars [groups]
  (let [clis (atom [])]
    (client/with-connection-pool connection-pool-defaults
      (doseq [group groups]
        (->> (client/get (str "https://clojars.org/api/groups/" group) {:accept           :application/edn
                                                                        :throw-exceptions false
                                                                        :as               :clojure})
          :body
          (swap! clis concat))))
    (keep (partial ->dep :group_name :jar_name :latest_version) @clis)))

(defn- fetch-from-mvn [groups]
  (let [clis (atom [])]
    (client/with-connection-pool connection-pool-defaults
      (doseq [group groups]
        (->> (client/get "https://search.maven.org/solrsearch/select"
               {:throw-exceptions false
                :accept           :json
                :query-params     {:q    (str "g:\"" group "\"")
                                   :wt   "json"
                                   :rows 1000}
                :as               :json})
          :body
          :response
          :docs
          (filter (comp (partial = "jar") :p))
          (swap! clis concat))))
    (keep (partial ->dep :g :a :latestVersion) @clis)))

(defn- print-clis [deps-v]
  (println "Downloading CLIs:")
  (mapv (fn [[cli version]]
          (println \tab cli version))
    deps-v)
  deps-v)

(when (seq groups)
  (some->> (concat
             (fetch-from-clojars groups)
             (fetch-from-mvn groups))
    seq
    print-clis
    deps))
EOF
	echo "$clj_script" > "$tmpdir/cljog_update.clj"
	run_script "$tmpdir/cljog_update.clj" "$namespaces"
}

if test -f "$1";then
	run_script "${@:1}"
else
	config_file=$HOME/.cljog

	sed_escape() {
		sed -e 's/[]\/$*.^[]/\\&/g'
	}

	cfg_delete() { # key
		test -f "$config_file" && sed -i.bak "/^$(echo $1 | sed_escape)/d" "$config_file" && rm "${config_file}.bak"
	}

	cfg_write() { # key, value
		cfg_delete "$1"
		echo "$1=$2" >> "$config_file"
	}

	cfg_read() { # key
		test -f "$config_file" && grep "^$(echo "$1" | sed_escape)=" "$config_file" | sed "s/^$(echo "$1" | sed_escape)=//" | tail -1
	}

	cfg_haskey() { # key
		test -f "$config_file" && grep "^$(echo "$1" | sed_escape)=" "$config_file" > /dev/null
	}

	if [[ ! -f "$config_file" ]];then
		log "Initialising config file: $config_file"
		touch "$config_file"
		cfg_write discovery_namespaces ""
		if hash mvn 2>/dev/null;then
			repo_path=$(mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)
			cfg_write repository "$(dirname $repo_path)"
		else
			cfg_write repository ""
		fi
	fi

	mvn_home=$(cfg_read repository)
	local_repo="$mvn_home/repository"
	namespaces=$(cfg_read discovery_namespaces)

	assert_repo_root(){
		if [[ -z "$mvn_home" ]];then
			error_exit "'repository' config value is not set.\nRun 'cljog --config-set repository /path/to/.m2' to configure."
		elif [[ ! -d "$local_repo" ]];then
			error_exit "'repository' directory ($local_repo) not found."
		fi
	}

	assert_namespace_config(){
		if [[ -z "$namespaces" ]];then
			error_exit "'discovery_namespaces' config value is not set.\nRun 'cljog --config-set discovery_namespaces your.first.ns,your.second.ns' to configure."
		fi
	}

	declare -A clis

	discover_clis() {
		assert_repo_root
		assert_namespace_config
		namespaces=(${namespaces//,/ })
		for i in ${!namespaces[@]};do
			namespaces[$i]="${local_repo}/${namespaces[$i]//./\/}"
		done
		local artifacts=$(find ${namespaces[@]} -name *.jar 2>/dev/null | tac)
		local repo_dir_str_length=$((${#local_repo} + 1))
		for artifact in ${artifacts};do
			local artifact="${artifact:$repo_dir_str_length}"
			local groupId=$(echo "$artifact" | rev | cut -d/ -f4- | rev | tr / .)
			local artifactId=$(echo "$artifact" | awk -F/ '{print $(NF-2)}')
			local version=$(echo "$artifact" | awk -F/ '{print $(NF-1)}')
			local cli="$groupId/$artifactId"
			local knownVersion=${clis["$cli"]}
			if [[ ${version} > ${knownVersion} ]];then
				clis["$cli"]="$version"
			fi
		done
	}

	list_clis() {
		hash column 2>/dev/null || error_exit "'column' command not found."
		echo "Local Commands in: $local_repo"
		local tty_width=$(stty size | awk '{print $2}')
		for dep in "${!clis[@]}";do
			local artifact=$(echo "$dep" | awk -F/ '{print $NF}')
			local version="${clis[$dep]}"
			local pom="$local_repo/$(echo "$dep" | tr . /)/$version/*$version.pom"
			pom=$(realpath ${pom})
			local groupId=$(echo ${dep} | cut -d/ -f1)
			if test -f "$pom";then
				echo -e "    $artifact\t$groupId\t$version\t$(awk -F '[<>]' '/description/{print $3}' "$pom")"
			fi
		done | column -ts $'\t' | sort | cut -b -${tty_width}
	}

	run_cli(){
		local dep
		local version
		for cli in "${!clis[@]}";do
			if [[ "$cli" == */${1} ]];then
				dep=$cli
				version="${clis[$cli]}"
				break
			fi
		done
		if [[ -n "$version" ]];then
				local DEPS="{:paths [] :deps {$dep {:mvn/version \"${version}\"}}}"
				local ns=$(echo $cli | tr / .)
				exec clojure $CLJ_OPTS -Sdeps "$DEPS" -m ${ns}.core "${@:2}"
		else
			error_exit "Unable to find cli '$1'. Run 'cljog --list' to see a list of all available commands"
		fi
	}

	config () {
		if [[ -n "$1" ]] && [[ -n "$2" ]];then
			cfg_write "$1" "$2"
		elif [[ -n "$1" ]];then
			cfg_delete "$1"
		fi
	}

	case "$1" in
		--config)
			log "${config_file}\n"
			cat ${config_file};;
		--config-get)
			cfg_read "$2";;
		--config-set)
			config "${@:2}";;
		--update|-u)
			assert_namespace_config
			log "Updating CLIs for $namespaces"
			update_clis "$namespaces";;
		--list|-l)
			discover_clis
			list_clis;;
		--version)
			echo "$VERSION";;
		""|--help)
			define usage <<EOF
command discovery
	'cljog --list'                   Prints a list of installed commands
	'cljog --update'                 Search for, installs, and updates commands matching
	                                 the configured 'discovery_namespaces' config
	'cljog cmd [arg1] [arg2] [arg3]' Runs an installed command with provided args

config
	'cljog --config'                 Print the entire config
	'cljog --config-set key [value]' Set (or clear) a config value
	'cljog --config-get key'         Get a config value

miscellaneous
	'cljog --version'                Prints the current version
EOF
			echo -e "$usage";;
		*)
			discover_clis
			run_cli "${@:1}";;
	esac
fi
